import re
import sys
from datetime import datetime
from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as pkg_version
from pathlib import Path

import click

if sys.version_info >= (3, 11):
    import tomllib
else:
    import tomli as tomllib

from .xdg import get_config_dir, get_config_paths

_DEFAULT_CONFIG_CONTENT = """\
# five-clis configuration file
# Generated by: five-clis --init-config
# All keys are optional. Uncomment to activate.

# ----- Display -----

# Terminal colour theme.
# Choices: default, dark, light, mono, rainbow
# Equivalent to: --theme <name>
# theme = "default"

# ----- Seasonal colours -----

# Apply seasonal ANSI colours based on the current date.
# Equivalent to: --seasonal-colours / --no-seasonal-colours
# seasonal-colours = true

# Which cultural calendar drives the seasonal colour scheme.
# Choices: western, jewish, islamic, hindu, sikh, east-asian
# Equivalent to: --seasonal-calendar <name>
# seasonal-calendar = "western"

# ----- Caching -----

# Enable disk caching of API responses.
# Equivalent to: --cache / --no-cache
# cache = false

# How long to cache results. Accepts seconds (300), or suffixed strings (5m, 2h).
# Equivalent to: --cache-ttl <value>
# cache-ttl = "300"

# ----- Updates -----

# Disable the automatic update check.
# Equivalent to: --no-update-check
# no-update-check = false
"""


def load_config(config_path: str | None = None) -> dict:
    """Load TOML config from *config_path* or the standard XDG search paths.

    Returns an empty dict if no config file is found.
    """
    if config_path:
        paths = [Path(config_path)]
    else:
        paths = get_config_paths()

    for path in paths:
        if path.exists():
            try:
                return tomllib.loads(path.read_text(encoding="utf-8"))
            except tomllib.TOMLDecodeError as exc:
                raise ValueError(f"Config parse error in {path}: {exc}") from exc
    return {}


def write_default_config() -> Path:
    """Write the default config to the XDG config directory.

    Returns the path written. Raises ``OSError`` on failure.
    """
    config_dir = get_config_dir()
    config_dir.mkdir(parents=True, exist_ok=True)
    config_path = config_dir / "config.toml"
    if not config_path.exists():
        config_path.write_text(_DEFAULT_CONFIG_CONTENT, encoding="utf-8")
    return config_path


def show_config(cfg: dict, config_path: str | None = None) -> str:
    """Return a human-readable summary of the resolved config."""
    lines = []
    if config_path:
        lines.append(f"Config file: {config_path}")
    else:
        found = next((p for p in get_config_paths() if p.exists()), None)
        lines.append(f"Config file: {found or '(none found)'}")
    lines.append("")
    if cfg:
        for key, value in sorted(cfg.items()):
            lines.append(f"  {key} = {value!r}")
    else:
        lines.append("  (no config keys set)")
    return "\n".join(lines)


def _extract_option_blocks(content: str) -> list[tuple[str, str]]:
    """Parse a config template into (key, block_text) pairs.

    Each block_text is the comment run leading up to (and including)
    the option definition line ``# key = default_value``.
    """
    lines = content.splitlines(keepends=True)
    results: list[tuple[str, str]] = []
    block_start: int | None = None

    for i, line in enumerate(lines):
        bare = line.rstrip("\n").strip()

        if bare == "" or re.match(r"^# [-=]{5,}", bare):
            block_start = None
            continue

        if bare.startswith("#"):
            if block_start is None:
                block_start = i
            m = re.match(r"^# ([a-z][a-z0-9-]+) =", bare)
            if m:
                key = m.group(1)
                block_text = "".join(lines[block_start : i + 1]).rstrip()
                results.append((key, block_text))
                block_start = None

    return results


def _key_present_in_file(key: str, content: str) -> bool:
    """Return True if *key* appears as an active or commented option."""
    pattern = rf"^#?\s*{re.escape(key)}\s*="
    return bool(re.search(pattern, content, re.MULTILINE))


def update_config(config_path: str | None = None) -> bool:
    """Append any missing options to the existing config file.

    Resolves the config file using the same priority order as load_config().
    Creates a timestamped backup before making any changes. Returns True on
    success (including when already up to date) and False on error.
    """
    if config_path:
        paths = [Path(config_path)]
    else:
        paths = get_config_paths()

    existing_path = next((p for p in paths if p.exists()), None)

    if existing_path is None:
        click.echo(
            click.style(
                "No config file found. Run five-clis --init-config to create one.",
                fg="red",
                bold=True,
            ),
            err=True,
        )
        return False

    click.echo(f"📋 Updating config at {existing_path}", err=True)

    try:
        existing_content = existing_path.read_text(encoding="utf-8")
    except OSError as exc:
        click.echo(click.style(f"Error reading config: {exc}", fg="red"), err=True)
        return False

    option_blocks = _extract_option_blocks(_DEFAULT_CONFIG_CONTENT)
    missing = [
        (key, block)
        for key, block in option_blocks
        if not _key_present_in_file(key, existing_content)
    ]

    if not missing:
        click.echo(
            click.style("✅ Config is already up to date.", fg="green"), err=True
        )
        return True

    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    backup_path = existing_path.parent / (existing_path.name + f".bak.{timestamp}")
    try:
        backup_path.write_text(existing_content, encoding="utf-8")
    except OSError as exc:
        click.echo(click.style(f"Error writing backup: {exc}", fg="red"), err=True)
        return False
    click.echo(f"💾 Backup saved to {backup_path}", err=True)

    try:
        _version = pkg_version("fiveclis")
    except PackageNotFoundError:
        _version = "unknown"

    readable_ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    separator = (
        f"# --- Added by --update-config (five-clis v{_version}) on {readable_ts} ---"
    )

    new_content = existing_content
    if not new_content.endswith("\n"):
        new_content += "\n"
    new_content += f"\n{separator}\n"
    for _key, block in missing:
        new_content += f"\n{block}\n"

    try:
        existing_path.write_text(new_content, encoding="utf-8")
    except OSError as exc:
        click.echo(click.style(f"Error writing config: {exc}", fg="red"), err=True)
        return False

    click.echo(
        click.style(f"✅ Added {len(missing)} missing option(s):", fg="green"), err=True
    )
    for key, _ in missing:
        click.echo(f"   {key}", err=True)

    return True
